Trainers2:

BillGroup:
	db "BILL@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, EEVEE, BRIGHTPOWDER
		db BODY_SLAM
		db GROWTH
		db DOUBLE_TEAM
		db BATON_PASS
	db 100, VAPOREON, LEFTOVERS
		db BUBBLEBEAM
		db AURORA_BEAM
		db ACID_ARMOR
		db BATON_PASS
	db 100, JOLTEON, SCOPE_LENS
		db THUNDERBOLT
		db PIN_MISSILE
		db AGILITY
		db BATON_PASS
	db 100, FLAREON, GOLD_BERRY
		db FLARE_BLITZ
		db FLAME_WHEEL
		db FOCUS_ENERGY
		db BATON_PASS
	db 100, ESPEON, MIRACLEBERRY
		db PSYCHIC_M
		db GROWTH
		db BARRIER
		db BATON_PASS
	db 100, UMBREON, QUICK_CLAW
		db DARK_PULSE
		db DOUBLE_TEAM
		db MEAN_LOOK
		db BATON_PASS
	db $ff ; end

	db "BILL@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_MAXXP)
	db 17, EEVEE
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db GROWL
	db 17, FLAREON
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db EMBER
	db 17, JOLTEON
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db THUNDERSHOCK
	db 17, VAPOREON
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db WATER_GUN
	db $ff ; end

ProfElmGroup:
	db "ELM@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, DONPHAN, LEFTOVERS
		db EARTHQUAKE
		db FLARE_BLITZ
		db ROLLOUT
		db DEFENSE_CURL
	db 100, AMPHAROS, GOLD_BERRY
		db THUNDERBOLT
		db DRAGON_PULSE
		db FOCUS_BLAST
		db AGILITY
	db 100, SLOWKING, QUICK_CLAW
		db PSYCHIC_M
		db SURF
		db BLIZZARD
		db FIRE_BLAST
	db 100, TYPHLOSION, CHARCOAL
		db FLAMETHROWER
		db EARTHQUAKE
		db SHADOW_BALL
		db WILD_CHARGE
	db 100, FERALIGATR, MYSTIC_WATER
		db WATERFALL
		db CRUNCH
		db ICE_PUNCH
		db OUTRAGE
	db 100, MEGANIUM, POWER_HERB
		db GIGA_DRAIN
		db DAZZLINGLEAM
		db EARTH_POWER
		db SOLARBEAM
	db $ff ; end

tppPcGroup:
	db "PC@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, MEWTWO, MIRACLEBERRY
		db PSYCHIC_M
		db THUNDERBOLT
		db ICE_BEAM
		db RECOVER
	db $ff

	db "PC@"
	db 0
	db $ff

	db "PC@"
	db 0
	db $ff

GiovanniGroup:
	db "GIOVANNI@"
	db (1 << TRAINERTYPE_MOVES) | ( 1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 60, MURKROW, SCOPE_LENS
		db DARK_PULSE
		db AIR_SLASH
		db AGILITY
		db SWAGGER
	db 62, DUGTRIO, BRIGHTPOWDER
		db DIG
		db SLASH
		db SANDSTORM
		db FISSURE
	db 63, NIDOQUEEN, GOLD_BERRY
		db POISON_JAB
		db EARTHQUAKE
		db THUNDER
		db BODY_SLAM
	db 63, NIDOKING, KINGS_ROCK
		db POISON_JAB
		db EARTHQUAKE
		db THUNDER
		db HORN_DRILL
	db 62, KANGASKHAN, BITTER_BERRY
		db THRASH
		db EARTHQUAKE
		db DYNAMICPUNCH
		db FISSURE
	db 65, RHYDON, FOCUS_BAND ; full restore target
		db EARTHQUAKE
		db ROCK_SLIDE
		db HORN_DRILL
		db FISSURE
	db $ff

	db "GIOVANNI@"
	db (1 << TRAINERTYPE_MOVES) | ( 1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 95, MURKROW, SCOPE_LENS
		db DARK_PULSE
		db AIR_SLASH
		db AGILITY
		db SWAGGER
	db 97, DUGTRIO, BRIGHTPOWDER
		db DIG
		db SLASH
		db SANDSTORM
		db EARTHQUAKE
	db 98, NIDOQUEEN, GOLD_BERRY
		db POISON_JAB
		db EARTHQUAKE
		db THUNDER
		db BLIZZARD
	db 98, NIDOKING, KINGS_ROCK
		db POISON_JAB
		db EARTHQUAKE
		db THUNDER
		db FIRE_BLAST
	db 97, KANGASKHAN, BITTER_BERRY
		db THRASH
		db EARTHQUAKE
		db DYNAMICPUNCH
		db OUTRAGE
	db 100, RHYDON, FOCUS_BAND ; full restore target
		db EARTHQUAKE
		db ROCK_SLIDE
		db FISSURE
		db HORN_DRILL
	db $ff

	db "GIOVANNI@"
	db (1 << TRAINERTYPE_MOVES) | ( 1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 24, RHYHORN, BERSERK_GENE
		db HORN_ATTACK
		db 0
		db 0
		db 0
	db 29, PERSIAN, NO_ITEM
		db SLASH
		db BITE
		db SCREECH
		db FAINT_ATTACK
	db 35, NIDOKING, NO_ITEM ; full restore target
		db POISON_JAB
		db DRILL_RUN
		db THRASH
		db HORN_DRILL
	db $ff

CoolSiblingsGroup:
	db "ELAN & IDA@"
	db (1 << TRAINERTYPE_MOVES)
	db 71, PORYGON2 ; hyper potion target
		db TRI_ATTACK
		db BLIZZARD
		db MIND_READER
		db ZAP_CANNON
	db 70, AZUMARILL
		db PLAY_ROUGH
		db BELLY_DRUM
		db DOUBLE_EDGE
		db AQUA_JET
	db $ff

	db "ELAN & IDA@"
	db (1 << TRAINERTYPE_MOVES)
	db 70, AZUMARILL
		db PLAY_ROUGH
		db BELLY_DRUM
		db DOUBLE_EDGE
		db AQUA_JET
	db 71, PORYGON2 ; hyper potion target
		db TRI_ATTACK
		db BLIZZARD
		db MIND_READER
		db ZAP_CANNON
	db $ff

	db "ARA & BELLA@"
	db (1 << TRAINERTYPE_MOVES)
	db 72, STANTLER ; hyper potion target
		db ZEN_HEADBUTT
		db THRASH
		db THUNDER_WAVE
		db HI_JUMP_KICK
	db 71, TAUROS
		db OUTRAGE
		db HORN_DRILL
		db EARTHQUAKE
		db DOUBLE_EDGE
	db $ff

	db "ARA & BELLA@"
	db (1 << TRAINERTYPE_MOVES)
	db 71, TAUROS
		db OUTRAGE
		db HORN_DRILL
		db EARTHQUAKE
		db DOUBLE_EDGE
	db 72, STANTLER ; hyper potion target
		db ZEN_HEADBUTT
		db THRASH
		db THUNDER_WAVE
		db HI_JUMP_KICK
	db $ff

	db "MING & LEE@"
	db 0
	db 95, DRAGONITE
	db 95, KINGDRA
	db $ff

	db "MING & LEE@"
	db 0
	db 95, KINGDRA
	db 95, DRAGONITE
	db $ff

RivalRBGroup:
; battle 1 - OAK's LAB
	db "<GREEN>@"
	db 0
	db 5, SQUIRTLE
	db $ff

	db "<GREEN>@"
	db 0
	db 5, BULBASAUR
	db $ff

	db "<GREEN>@"
	db 0
	db 5, CHARMANDER
	db $ff

; battle 2 - ROUTE 22
	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 6, RATTATA
		db TACKLE
		db TAIL_WHIP
		db 0
		db 0
	db 8, SQUIRTLE
		db TACKLE
		db TAIL_WHIP
		db BUBBLE
		db 0
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 6, RATTATA
		db TACKLE
		db TAIL_WHIP
		db 0
		db 0
	db 8, BULBASAUR
		db TACKLE
		db GROWL
		db VINE_WHIP
		db 0
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 6, RATTATA
		db TACKLE
		db TAIL_WHIP
		db 0
		db 0
	db 8, CHARMANDER
		db SCRATCH
		db GROWL
		db EMBER
		db 0
	db $ff

; battle 3 - CERULEAN CITY
	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 14, RATTATA, NO_ITEM
		db TACKLE
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 14, PIDGEY, NO_ITEM
		db GUST
		db SAND_ATTACK
		db QUICK_ATTACK
		db 0
	db 14, PIKACHU, NO_ITEM
		db THUNDERSHOCK
		db GROWL
		db TAIL_WHIP
		db QUICK_ATTACK
	db 15, SQUIRTLE, BERRY
		db TACKLE
		db BUBBLE
		db WITHDRAW
		db WATER_GUN
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 14, RATTATA, NO_ITEM
		db TACKLE
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 14, PIDGEY, NO_ITEM
		db GUST
		db SAND_ATTACK
		db QUICK_ATTACK
		db 0
	db 14, PIKACHU, NO_ITEM
		db THUNDERSHOCK
		db GROWL
		db TAIL_WHIP
		db QUICK_ATTACK
	db 15, BULBASAUR, BERRY
		db TACKLE
		db VINE_WHIP
		db LEECH_SEED
		db POISONPOWDER
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 14, RATTATA, NO_ITEM
		db TACKLE
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 14, PIDGEY, NO_ITEM
		db GUST
		db SAND_ATTACK
		db QUICK_ATTACK
		db 0
	db 14, PIKACHU, NO_ITEM
		db THUNDERSHOCK
		db GROWL
		db TAIL_WHIP
		db QUICK_ATTACK
	db 15, CHARMANDER, BERRY
		db SCRATCH
		db EMBER
		db METAL_CLAW
		db SMOKESCREEN
	db $ff

; battle 4 - ST.ANNE
	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 17, PIDGEOTTO, NO_ITEM
		db GUST
		db SAND_ATTACK
		db QUICK_ATTACK
		db 0
	db 16, PIKACHU, NO_ITEM
		db THUNDERSHOCK
		db QUICK_ATTACK
		db THUNDER_WAVE
		db DOUBLE_TEAM
	db 15, CUBONE, NO_ITEM
		db BONE_CLUB
		db GROWL
		db TAIL_WHIP
		db HEADBUTT
	db 14, VULPIX, NO_ITEM
		db EMBER
		db TAIL_WHIP
		db QUICK_ATTACK
		db 0
	db 14, BELLSPROUT, NO_ITEM
		db VINE_WHIP
		db GROWTH
		db WRAP
		db 0
	db 18, WARTORTLE, BERRY
		db BUBBLE
		db WITHDRAW
		db WATER_GUN
		db BITE
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 17, PIDGEOTTO, NO_ITEM
		db GUST
		db SAND_ATTACK
		db QUICK_ATTACK
		db 0
	db 16, PIKACHU, NO_ITEM
		db THUNDERSHOCK
		db QUICK_ATTACK
		db THUNDER_WAVE
		db DOUBLE_TEAM
	db 15, CUBONE, NO_ITEM
		db BONE_CLUB
		db GROWL
		db TAIL_WHIP
		db HEADBUTT
	db 14, STARYU, NO_ITEM
		db TACKLE
		db HARDEN
		db WATER_GUN
		db 0
	db 14, VULPIX, NO_ITEM
		db EMBER
		db TAIL_WHIP
		db QUICK_ATTACK
		db 0
	db 18, IVYSAUR, BERRY
		db VINE_WHIP
		db LEECH_SEED
		db POISONPOWDER
		db SLEEP_POWDER
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 17, PIDGEOTTO, NO_ITEM
		db GUST
		db SAND_ATTACK
		db QUICK_ATTACK
		db 0
	db 16, PIKACHU, NO_ITEM
		db THUNDERSHOCK
		db QUICK_ATTACK
		db THUNDER_WAVE
		db DOUBLE_TEAM
	db 15, CUBONE, NO_ITEM
		db BONE_CLUB
		db GROWL
		db TAIL_WHIP
		db HEADBUTT
	db 14, BELLSPROUT, NO_ITEM
		db VINE_WHIP
		db GROWTH
		db WRAP
		db 0
	db 14, STARYU, NO_ITEM
		db TACKLE
		db HARDEN
		db WATER_GUN
		db 0
	db 18, CHARMELEON, BERRY
		db EMBER
		db METAL_CLAW
		db SMOKESCREEN
		db RAGE
	db $ff

; battle 5 - INDIGO PLATEAU
	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 61, PIDGEOT, POWER_HERB
		db WING_ATTACK
		db SAND_ATTACK
		db SKY_ATTACK
		db WHIRLWIND
	db 61, RAICHU, GOLD_BERRY
		db THUNDERBOLT
		db IRON_TAIL
		db SURF
		db WILD_CHARGE
	db 61, MAROWAK, THICK_CLUB
		db BONEMERANG
		db ROCK_SLIDE
		db PERISH_SONG
		db EARTHQUAKE
	db 61, NINETALES, CHARCOAL
		db FLAMETHROWER
		db SHADOW_BALL
		db HIDDEN_POWER
		db CURSE
	db 61, VICTREEBEL, MIRACLE_SEED
		db GIGA_DRAIN
		db SLUDGE_BOMB
		db SLEEP_POWDER
		db REFLECT
	db 65, BLASTOISE, LEFTOVERS
		db HYDRO_PUMP
		db ICE_BEAM
		db EARTHQUAKE
		db BLIZZARD
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 61, PIDGEOT, POWER_HERB
		db WING_ATTACK
		db SAND_ATTACK
		db SKY_ATTACK
		db WHIRLWIND
	db 61, RAICHU, GOLD_BERRY
		db THUNDERBOLT
		db IRON_TAIL
		db SURF
		db WILD_CHARGE
	db 61, MAROWAK, THICK_CLUB
		db BONEMERANG
		db ROCK_SLIDE
		db PERISH_SONG
		db EARTHQUAKE
	db 61, STARMIE, MYSTIC_WATER
		db SURF
		db PSYCHIC_M
		db ICE_BEAM
		db CONFUSE_RAY
	db 61, NINETALES, CHARCOAL
		db FLAMETHROWER
		db SHADOW_BALL
		db HIDDEN_POWER
		db CURSE
	db 65, VENUSAUR, LEFTOVERS
		db SOLARBEAM
		db SLUDGE_BOMB
		db EARTHQUAKE
		db GIGA_DRAIN
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 61, PIDGEOT, POWER_HERB
		db WING_ATTACK
		db SAND_ATTACK
		db SKY_ATTACK
		db WHIRLWIND
	db 61, RAICHU, GOLD_BERRY
		db THUNDERBOLT
		db IRON_TAIL
		db SURF
		db WILD_CHARGE
	db 61, MAROWAK, THICK_CLUB
		db BONEMERANG
		db ROCK_SLIDE
		db PERISH_SONG
		db EARTHQUAKE
	db 61, VICTREEBEL, MIRACLE_SEED
		db GIGA_DRAIN
		db SLUDGE_BOMB
		db SLEEP_POWDER
		db REFLECT
	db 61, STARMIE, MYSTIC_WATER
		db SURF
		db PSYCHIC_M
		db ICE_BEAM
		db CONFUSE_RAY
	db 65, CHARIZARD, LEFTOVERS
		db FIRE_BLAST
		db DRAGON_PULSE
		db WING_ATTACK
		db EARTHQUAKE
	db $ff


; battle 6 - CHAMPION REMATCH
	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, ARTICUNO, LEFTOVERS
		db ICE_BEAM
		db BUBBLEBEAM
		db HIDDEN_POWER ; grass
		db REFLECT
	db 100, ZAPDOS, LEFTOVERS
		db THUNDERBOLT
		db DRILL_PECK
		db HIDDEN_POWER ; grass
		db THUNDER_WAVE
	db 100, MOLTRES, LEFTOVERS
		db FLAMETHROWER
		db DOUBLE_EDGE
		db HIDDEN_POWER ; grass
		db FIRE_BLAST
	db 100, SNORLAX, LEFTOVERS
		db BODY_SLAM
		db EARTHQUAKE
		db CURSE
		db REST
	db 100, LAPRAS, LEFTOVERS
		db SURF
		db ICE_BEAM
		db THUNDERBOLT
		db CONFUSE_RAY
	db 100, MEW, LEFTOVERS
		db PSYCHIC_M
		db EARTHQUAKE
		db ICE_BEAM
		db SOFTBOILED
	db $ff

BrockRBGroup:
	db "BROCK@" ; if the player picked charmander
	db (1 << TRAINERTYPE_MOVES)
	db 10, GEODUDE
		db TACKLE
		db DEFENSE_CURL
		db ROLLOUT
		db SANDSTORM
	db 12, ONIX ; potion target
		db BIDE
		db WRAP
		db IRON_TAIL
		db SANDSTORM
	db $ff ; end

	db "BROCK@" ; if the player picked bulbasaur/squirtle
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_MAXXP)
	db 10, GEODUDE
		db TACKLE
		db DEFENSE_CURL
		db ROLLOUT
		db SANDSTORM
	db 12, ONIX ; potion target
		db BIDE
		db WRAP
		db IRON_TAIL
		db SANDSTORM
	db $ff ; end

MistyRBGroup:
	db "MISTY@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 15, STARYU, STARDUST
		db SWIFT
		db RAIN_DANCE
		db RAPID_SPIN
		db BUBBLE
	db 18, STARMIE, STAR_PIECE ; fresh water target
		db BUBBLEBEAM
		db CONFUSION
		db SWIFT
		db HARDEN
	db $ff ; end

BabaGroup:
	db "KRIS@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, RAIKOU, FOCUS_BAND
		db THUNDERBOLT
		db CRUNCH
		db IRON_HEAD
		db HIDDEN_POWER ; ice
	db 100, ENTEI, SCOPE_LENS
		db FIRE_BLAST
		db CRUNCH
		db IRON_HEAD
		db HIDDEN_POWER ; ground
	db 100, SUICUNE, BRIGHTPOWDER
		db SURF
		db ICE_BEAM
		db ROAR
		db HIDDEN_POWER ; grass
	db 100, CELEBI, MIRACLEBERRY
		db PSYCHIC_M
		db GIGA_DRAIN
		db RECOVER
		db LEECH_SEED
	db 100, LUGIA, LEFTOVERS
		db AEROBLAST
		db PSYCHIC_M
		db EARTHQUAKE
		db SURF
	db 100, HO_OH, QUICK_CLAW
		db SACRED_FIRE
		db THUNDER
		db EARTHQUAKE
		db GIGA_DRAIN
	db $ff

ExecutiveEgkGroup:
	db "EXECUTIVE@"
	db (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MOVES)
	db 16, RATICATE, BERSERK_GENE
		db HYPER_FANG
		db BITE
		db QUICK_ATTACK
		db 0
	db $ff
